project:
  type: website
  output-dir: docs

website:
  title: "Workshop TDA"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Presentación
      - introduccion.qmd
      - vietoris_rips.qmd
      #- homologia.qmd
      - wasserstein.qmd
      - clustering.qmd
      - topkat.qmd
      - proyecto.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    toc-depth: 2
    toc-expand: 2
    number-sections: true
    number-depth: 2
    code-copy: true
    code-fold: show
    code-summary: "Mostrar código"
    code-tools: true
    code-overflow: wrap
    page-layout: article

editor: visual



