project:
  type: website

website:
  title: "Workshop TDA"

  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Inicio

      - introduccion.qmd
      - vietoris_rips.qmd
      - homologia.qmd
      - diagramas.qmd
      - wasserstein.qmd
      - clustering.qmd
      - topkat.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    page-layout: article